### ISSUE TITLE
Issue with historic high-tide flood counts

### ISSUE THREAD

**Issue by daveism** [nemac/climate-explorer#113]
source for the flood counts that matches what the other NOAA tools show:
Check https://tidesandcurrents.noaa.gov/dpapi/latest/ under Yearly Inundation Statistics. The page also offers examples of calls.

CE was using the May-April counts (as barely noted at the end of a comment in cell 6B of the .csv we use), but the other tools are showing Jan-Dec counts via the API. 

Updating CE to show this data source will align our results with those of other tools, and all will show Jan-Dec counts.

**Comment by jwilson8767** [comment]
Resolved as part of CE 3.1
