### ISSUE TITLE
Climate by Location hover template changes (2)

### ISSUE THREAD

**Issue by cmy2k** [nemac/climate-explorer#133]
Known limitations with Plotly:
- Cannot change year label on top of box
- Have access to year as variable (do not have name of month)
- There must be one trace per legend entry
- Grouping is tied to visibility, so in order to have RCP8.5 turn on and off RCP8.5 has to be grouped together in legend
- Can have baseline for historic, not proj
- Based on historical ordering of colors and bands, if we change the order so that higher emissions comes first, it will not look the same.
- MAY be limits to width of text in legend entries, we aren't sure yet at what point the legend may get clipped

_Suggested text for x = 1950-2004_
Range of hindcast values = [historical modeled Ymin-Ymax]
Observed average for [year] = [value from Livneh]
Average from 1961-1990 = [1961-1990 average]

_Suggested text for x = 2005-2099_
For lower emissions, projected average for [year] = [weighted average of lower emissions projections] 
Range of projections for lower emissions = [Ymin-Ymax for lower emissions] 
For higher emissions, projected average for [year] = [weighted average of higher emissions projections]
Range of projections for higher emissions = [Ymin-Ymax for higher emissions] 

Observed average for [year] = [value from Livneh] <---- This line would only appear up to = 2013 (last year of Livneh record)
Average from 1961-1990 = [1961-1990 avg]

**Comment by jwilson8767** [comment]
Final text templates will look like:

(for x = 1950-2004)
Range of hindcast values = [decadal average of Ymin- decadal average of Ymax for historical modeled]
Observed average for [year] = [value from Livneh]
Average from 1961-1990 = [1961-1990 average]

(x = 2005-2099)
For lower emissions, projected average for [decade] = [decadal average of weighted averages of lower emissions projections] 
Range of projections for lower emissions = [decadal average of Ymin- decadal average of Ymax for lower emissions] 
For higher emissions, projected average for [decade] = [decadal average of weighted average of higher emissions projections]
Range of projections for higher emissions = [decadal average of Ymin- decadal average of Ymax for higher emissions]
