### ISSUE TITLE
Comments from social media

### ISSUE THREAD

**Issue by LuAnn** [nemac/climate-explorer#54]
Just dropping these 2 comments from our social media editor here until I have chance to deal with them:

From facebook, our resident Alaskan noted that it should say contiguous US and not continental in the national maps section when you scroll to areas outside the contiguous US. This is in the orange box that says "The location on the map is outside the Continental US".

And from me: I'm glad to see that when you download a spatial map image that the colorbar is attached. However, when you download the local climate chart time series, the legends (high emissions, lower emissions, historical modeled etc) are not included in the image download. Is there a way of changing that?

^ If you see good solutions to these issues, feel free to make them. If not, I'm happy to discuss what we ought to do with them.

**Comment by daveism** [comment]
Fixing text now.

As for adding legends to the chart download that is not possible with the current charting library. Something to put on the roadmap for the next update.
